---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: package-admin
  namespace: argocd
  # finalizers:  # Add a this finalizer ONLY if you want these to cascade delete.
  #   - resources-finalizer.argocd.argoproj.io  
spec:
  project: default
  source:
    directory:
      recurse: true
    repoURL: https://github.com/robparrott/k8s-gitops-stack-admin.git
    targetRevision: HEAD
    path: modules
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd

  # Sync policy
  syncPolicy:
    automated:
      prune: false # Specifies if resources should be pruned during auto-syncing ( false by default ).
      selfHeal: false # Specifies if partial app sync should be executed when resources are changed only in target Kubernetes cluster and no git change detected ( false by default ).
